SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'feedback_multiple'
AND TABLE_SCHEMA = DATABASE()
AND COLUMN_NAME != 'prognosis'
AND ORDINAL_POSITION < (
    SELECT ORDINAL_POSITION
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'feedback_multiple'
    AND TABLE_SCHEMA = DATABASE()
    AND COLUMN_NAME = 'prognosis'
)
ORDER BY ORDINAL_POSITION DESC
LIMIT 1;