CREATE TABLE IF NOT EXISTS feedback_multiple (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prognosis VARCHAR(255) NOT NULL,
    user_feedback BOOLEAN NOT NULL DEFAULT 0,
    feedback_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    correct_diagnosis VARCHAR(255) NOT NULL
);
